/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.sao_legacy;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import net.mcreator.sao_legacy.gui.GuiForgeGUI;
import net.mcreator.sao_legacy.gui.GuiDeconstructor;
import net.mcreator.sao_legacy.gui.GuiColPouchFiller;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsTheSAOLegacyMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsTheSAOLegacyMod() {
		sounds.put(new ResourceLocation("sao_legacy", "confront_battle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "confront_battle")));
		sounds.put(new ResourceLocation("sao_legacy", "a_close_battle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_close_battle")));
		sounds.put(new ResourceLocation("sao_legacy", "a_narrow_escape"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_narrow_escape")));
		sounds.put(new ResourceLocation("sao_legacy", "a_squabble"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_squabble")));
		sounds.put(new ResourceLocation("sao_legacy", "a_strategy_meeting"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_strategy_meeting")));
		sounds.put(new ResourceLocation("sao_legacy", "a_tender_feeling"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_tender_feeling")));
		sounds.put(new ResourceLocation("sao_legacy", "a_tense_situation"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_tense_situation")));
		sounds.put(new ResourceLocation("sao_legacy", "a_tiny_love"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_tiny_love")));
		sounds.put(new ResourceLocation("sao_legacy", "a_brisk_conversation"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "a_brisk_conversation")));
		sounds.put(new ResourceLocation("sao_legacy", "aincrad"), new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "aincrad")));
		sounds.put(new ResourceLocation("sao_legacy", "at_nightfall"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "at_nightfall")));
		sounds.put(new ResourceLocation("sao_legacy", "at_our_parting"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "at_our_parting")));
		sounds.put(new ResourceLocation("sao_legacy", "at_our_parting_cello"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "at_our_parting_cello")));
		sounds.put(new ResourceLocation("sao_legacy", "critical_phase"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "critical_phase")));
		sounds.put(new ResourceLocation("sao_legacy", "daily_life_you_and_me"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "daily_life_you_and_me")));
		sounds.put(new ResourceLocation("sao_legacy", "despaired"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "despaired")));
		sounds.put(new ResourceLocation("sao_legacy", "feel_uneasy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "feel_uneasy")));
		sounds.put(new ResourceLocation("sao_legacy", "fight"), new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "fight")));
		sounds.put(new ResourceLocation("sao_legacy", "fight_with_a_devil"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "fight_with_a_devil")));
		sounds.put(new ResourceLocation("sao_legacy", "got_to_win"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "got_to_win")));
		sounds.put(new ResourceLocation("sao_legacy", "gracefully"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "gracefully")));
		sounds.put(new ResourceLocation("sao_legacy", "he_rules_us"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "he_rules_us")));
		sounds.put(new ResourceLocation("sao_legacy", "i_wonder"), new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "i_wonder")));
		sounds.put(new ResourceLocation("sao_legacy", "in_your_past"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "in_your_past")));
		sounds.put(new ResourceLocation("sao_legacy", "left_in_suspense"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "left_in_suspense")));
		sounds.put(new ResourceLocation("sao_legacy", "looking_back_on_those_days"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "looking_back_on_those_days")));
		sounds.put(new ResourceLocation("sao_legacy", "luminous_sword"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "luminous_sword")));
		sounds.put(new ResourceLocation("sao_legacy", "march_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "march_down")));
		sounds.put(new ResourceLocation("sao_legacy", "no_way"), new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "no_way")));
		sounds.put(new ResourceLocation("sao_legacy", "quiet_strain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "quiet_strain")));
		sounds.put(new ResourceLocation("sao_legacy", "she_is_still_sleeping"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "she_is_still_sleeping")));
		sounds.put(new ResourceLocation("sao_legacy", "smile_for_me"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "smile_for_me")));
		sounds.put(new ResourceLocation("sao_legacy", "stand_at_bay"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "stand_at_bay")));
		sounds.put(new ResourceLocation("sao_legacy", "survive_the_swordland"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "survive_the_swordland")));
		sounds.put(new ResourceLocation("sao_legacy", "swordland"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "swordland")));
		sounds.put(new ResourceLocation("sao_legacy", "taut_nerves"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "taut_nerves")));
		sounds.put(new ResourceLocation("sao_legacy", "victory"), new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "victory")));
		sounds.put(new ResourceLocation("sao_legacy", "weird_place"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "weird_place")));
		sounds.put(new ResourceLocation("sao_legacy", "we_have_to_defeat_it"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "we_have_to_defeat_it")));
		sounds.put(new ResourceLocation("sao_legacy", "with_my_friend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "with_my_friend")));
		sounds.put(new ResourceLocation("sao_legacy", "yui"), new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "yui")));
		sounds.put(new ResourceLocation("sao_legacy", "everyday_life"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "everyday_life")));
		sounds.put(new ResourceLocation("sao_legacy", "the_first_town"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sao_legacy", "the_first_town")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsTheSAOLegacyMod.ModElement.class)
					elements.add((ElementsTheSAOLegacyMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsTheSAOLegacyMod.ModElement::initElements);
		this.addNetworkMessage(TheSAOLegacyModVariables.WorldSavedDataSyncMessageHandler.class,
				TheSAOLegacyModVariables.WorldSavedDataSyncMessage.class, Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = TheSAOLegacyModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = TheSAOLegacyModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				TheSAOLegacyMod.PACKET_HANDLER.sendTo(new TheSAOLegacyModVariables.WorldSavedDataSyncMessage(0, mapdata),
						(EntityPlayerMP) event.player);
			if (worlddata != null)
				TheSAOLegacyMod.PACKET_HANDLER.sendTo(new TheSAOLegacyModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = TheSAOLegacyModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				TheSAOLegacyMod.PACKET_HANDLER.sendTo(new TheSAOLegacyModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			TheSAOLegacyMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiColPouchFiller.GUIID)
				return new GuiColPouchFiller.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDeconstructor.GUIID)
				return new GuiDeconstructor.GuiContainerMod(world, x, y, z, player);
			if (id == GuiForgeGUI.GUIID)
				return new GuiForgeGUI.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiColPouchFiller.GUIID)
				return new GuiColPouchFiller.GuiWindow(world, x, y, z, player);
			if (id == GuiDeconstructor.GUIID)
				return new GuiDeconstructor.GuiWindow(world, x, y, z, player);
			if (id == GuiForgeGUI.GUIID)
				return new GuiForgeGUI.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsTheSAOLegacyMod elements;
		protected final int sortid;
		public ModElement(ElementsTheSAOLegacyMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
